version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.8.0
    steps:
      - checkout
      - run:
          name: npm ci
          command: npm ci
      - run:
          name: run tests
          command: npm test